Repository GSG-G13/E-commerce-team-7, pull requests merged in 2023-05, with the labels that each got.

#4 create build database file
  src/database/config/build.sql
  src/database/config/fakeData.sql
Labels: wating review

#6 react-setup-and-restructure-files
  .gitignore
  client/.eslintrc.cjs
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.jsx
  client/src/Components/Footer.jsx
  client/src/Components/Navbar.jsx
  client/src/Components/ProductCard.jsx
  client/src/Components/Products.jsx
  client/src/Components/index.js
  client/src/assets/index.js
  client/src/assets/react.svg
  client/src/assets/styles/cards.css
  client/src/assets/styles/index.js
  client/src/assets/styles/layout.css
  client/src/main.jsx
  client/vite.config.js
  package-lock.json
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/index.js
  server/src/index.js
  server/src/middlewares/index.js
  server/src/routes/index.js
  server/src/utils/index.js
Labels: Done

#9 set database connection
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/config/fakeData.sql
Labels: waiting review

#14 Create checkAuth middlewares & Promise verify, sign
  server/src/database/config/connection.js
  server/src/index.js
  server/src/middlewares/checkAuth.js
  server/src/middlewares/index.js
  server/src/utils/index.js
  server/src/utils/promisesSign.js
Labels: Done

#21 run checkAuth on delete router and create IsLogged middleware
  server/src/app.js
  server/src/controllers/auth/signup.js
  server/src/controllers/cart/addToCart.js
  server/src/controllers/cart/deleteProduct.js
  server/src/controllers/cart/getAllProductFromCart.js
  server/src/controllers/index.js
  server/src/controllers/login/login.js
  server/src/database/query/cart/addToCart.js
  server/src/database/query/cart/deleteFromCart.js
  server/src/database/query/index.js
  server/src/database/query/products/getProducts.js
  server/src/middleware/checkAuth.js
  server/src/middleware/client.js
  server/src/middleware/isLogged.js
  server/src/middleware/serverError.js
  server/src/routes/index.js
  server/src/utils/helper/promises.js
Labels: waiting review

#22 make refectoer and let cart functions work
  server/src/controllers/auth/signup.js
  server/src/controllers/cart/addToCart.js
  server/src/controllers/cart/deleteProduct.js
  server/src/controllers/cart/getAllProductFromCart.js
  server/src/controllers/login/login.js
  server/src/database/config/connection.js
  server/src/database/query/auth/signup.js
  server/src/database/query/cart/addToCart.js
  server/src/database/query/cart/deleteFromCart.js
  server/src/database/query/cart/getProductFromCart.js
  server/src/middleware/checkAuth.js
  server/src/middleware/isLogged.js
  server/src/middleware/serverError.js
  server/src/routes/index.js
  server/src/utils/helper/promises.js
Labels: waiting review

#24 react-setup-and-styles
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/.eslintrc.json
  client/src/Components/Products.jsx
  client/src/Pages/HomePage.jsx
  client/src/Pages/Login.jsx
  client/src/assets/index.js
  client/src/assets/styles/cards.css
  client/src/assets/styles/cart.css
  client/src/assets/styles/index.js
  client/src/assets/styles/layout.css
  client/src/assets/styles/login.css
  client/src/layout/RootLayout.jsx
  client/src/layout/index.jsx
Labels: Done

#35 setting up signin/up handlers
  client/src/Pages/AccessForm.jsx
  client/src/assets/styles/login.css
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/auth/signup.js
  server/src/controllers/cart/getAllProductFromCart.js
  server/src/controllers/login/login.js
  server/src/routes/index.js
  server/src/utils/helper/promises.js
Labels: Done

#44 finish product page fetch
  client/src/App.jsx
  client/src/Pages/ProductPage.jsx
  client/src/assets/styles/productPgae.css
  server/src/controllers/auth/signup.js
  server/src/controllers/cart/addToCart.js
  server/src/database/config/build.sql
  server/src/database/config/fakeData.sql
  server/src/database/query/cart/addToCart.js
  server/src/database/query/cart/count.js
  server/src/middleware/checkAuth.js
  server/src/routes/auth.js
  server/src/routes/cartRouter.js
  server/src/routes/index.js
Labels: waiting review

#49 Fix errors
  client/src/Components/cartComponents/cartDiv.jsx
  client/src/Pages/CartPage.jsx
  server/src/controllers/cart/deleteProduct.js
  server/src/database/query/cart/deleteFromCart.js
Labels: Done

#45 Counter function
  client/src/Components/NavBar.jsx
  client/src/Components/cartComponents/cartDiv.jsx
  client/src/Pages/AccessForm.jsx
  client/src/Pages/CartPage.jsx
  client/src/assets/styles/cart.css
  client/src/assets/styles/layout.css
  server/.eslintrc.json
  server/src/controllers/auth/logout.js
  server/src/controllers/cart/decrement.js
  server/src/controllers/cart/getAllProductFromCart.js
  server/src/controllers/index.js
  server/src/database/query/cart/count.js
  server/src/routes/index.js
  server/src/validation/userSchema/signupSchema.js
Labels: waiting review

#52 Add create checkAuth on navBar
  client/package-lock.json
  client/package.json
  client/src/Components/NavBar.jsx
  client/src/Pages/CartPage.jsx
  package.json
Labels: waiting review

#53 make pagention
  client/src/Components/ProductCard.jsx
  client/src/Pages/HomePage.jsx
Labels: waiting review

#55 refactor pagination buttons
  client/src/Components/ProductCard.jsx
  client/src/Pages/HomePage.jsx
Labels: Done

#58 Create search input
  client/src/Pages/HomePage.jsx
  server/src/database/config/fakeData.sql
Labels: waiting review

#59 54 re style
  changes.js
  client/src/Components/Footer.jsx
  client/src/Components/NavBar.jsx
  client/src/Components/ProductCard.jsx
  client/src/Pages/HomePage.jsx
  client/src/Pages/ProductPage.jsx
  client/src/assets/styles/cards.css
  client/src/assets/styles/cart.css
  client/src/assets/styles/footer.css
  client/src/assets/styles/layout.css
  client/src/assets/styles/productPgae.css
Labels: waiting review

#61 Testing
  server/.babelrc
  server/__tests__/jest.test.js
  server/jest.config.cjs
  server/package-lock.json
  server/package.json
  server/src/controllers/products/getProducts.js
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/config/fakeData.sql
Labels: waiting review

#62 Deploy
  changes.js
  client/index.html
  client/package.json
  client/src/Components/NavBar.jsx
  client/src/Components/ProductCard.jsx
  client/src/Pages/HomePage.jsx
  package-lock.json
  package.json
  server/src/app.js
  server/src/database/config/fakeData.sql
Labels: Done

#64 fix path and add the / endpoint
  server/src/app.js
Labels: Done

#68 fix deploy
  package.json
  server/package.json
  server/src/app.js
  server/src/middleware/customError.js
  server/src/middleware/serverError.js
Labels: waiting review

#74 Refactor
  client/src/Components/NavBar.jsx
  client/src/Components/ProductCard.jsx
  client/src/Pages/AccessForm.jsx
  client/src/Pages/CartPage.jsx
  client/src/Pages/HomePage.jsx
  client/src/assets/styles/cards.css
  client/src/assets/styles/layout.css
  client/src/assets/styles/login.css
  package.json
  server/src/app.js
  server/src/index.js
Labels: waiting review

#75 readme file
  README.md
Labels: waiting review

#76 fix start, dev commandes
  package.json
Labels: waiting review

#77 fix start, dev commandes
  package.json
Labels: waiting review

#78 fix start comand
  package.json
Labels: Done

#79 fix product image
  client/src/Pages/ProductPage.jsx
  package.json
Labels: waiting review

#80 mace redirect on product page
  client/src/Pages/ProductPage.jsx
Labels: Done
